### ISSUE TITLE
Matrix representation

### ISSUE THREAD

**Issue by mikegogulski** [conreality/consensus#12]
We need to decide if we're going to use row-major order or column-major order.

https://en.wikipedia.org/wiki/Row-major_order

Row-major is easier for me to wrap my head around, so I propose using that.

Blocks further matrix implementation until decided.

**Comment by mikegogulski** [comment]
Another issue to decide here is whether or not we use zero-basis or one-basis for element indices. Zero-basis seems the correct choice for a variety of reasons, but we must be aware that math texts and similar writing often uses one-basis.

**Comment by ab0032** [comment]
About this row major issue and the conventions used in directx and opengl
I've sent a link to Arto. I will try to find it.
My natural reaction would be to use row major too.

I would always use zero based indexing in programming.

Another convention to think about is how the coordinate system is related
to the vehicle. There are different conventions for land based cars, ships,
aircraft and spacecraft. https://en.wikipedia.org/wiki/Axes_conventions
Cars use ENU, aircraft use NED. Since I have been dealing with drones, my
thinking is more used to NED, but some of the drone software out there does
not adhere to this.

What should we do about this? Should we use something altogether different
to make the confusion perfect? ;-)

I would think having x and y horizontal and z to point up is natural.
(Horizontal disregarding the earths curvature.) But I have gotten used to
NED. To me making x go to the right/east is natural and y away from me to
the front/north and positive z to go up, but that would mean front is north
and we would neither be using ENU nor NED.

Euler angles: don't use them, use Tait-Bryan angles.
Of course you can represent every rotation by rotating about z, then y and
then z again. Please rotate about x, then y, then z. Or backwards, first z,
then y and finally x.
https://en.wikipedia.org/wiki/Euler_angles

And prevent methods which cause gimbal locking. This is something still
very common in computer graphics, even in googles sketchup it is present.
This problem is avoidable.
https://en.wikipedia.org/wiki/Gimbal_lock

a

**Comment by bendiken** [comment]
Ceteris paribus, we ought to follow the conventions of major pieces of hardware and software that we need to interface with for physics calculations and any rendering work. That means OpenCV and ROS initially, and OpenGL eventually. Of course, there is no guarantee these conventions all line up with each other, in which case we'll have to use further heuristics to settle on one.

My personal default in the past has always been to stick with the OpenGL system, which is a column-major [right-handed coordinate system](http://programmers.stackexchange.com/q/17519/14852) [to a first approximation](http://stackoverflow.com/a/12336360/320911). But perhaps a wider review here would be in order--this certainly isn't something we'd like to revisit and retool on going forward, so pays to make a good choice.

**Comment by ab0032** [comment]
I believe openGL has a switch for column major or row major I believe, but
I am not sure.

I can't find the piece I have sent to Arto which explained all this well,
because I sent it on fb and fb won't let me go far enough back in our
dialog and it won't let me search it.

Always use right handed coordinate systems please.

Another thing that comes to my mind in this context is whether one
multiplies matrices from the left or the right. Both are fine, but you have
to stick to one convention.

Yes, I agree we should stick to openCV and ROS conventions. I would give
openGL lower priority.

**Comment by ab0032** [comment]
The openGL faq states: "Column-major versus row-major is purely a
notational convention. Note that post-multiplying with column-major
matrices produces the same result as pre-multiplying with row-major
matrices. The OpenGL Specification and the OpenGL Reference Manual both use
column-major notation. You can use any notation, as long as it's clearly
stated."

I am starting to get confused.

**Comment by mikegogulski** [comment]
Alexander, thanks much for your input here.

To my OP here: row-major versus column-major is really just important to us in how we're going to think about and represent the data in code. If our default representation is row-major, it's easy enough to provide matrix operators that work on column-major arguments (and vice versa), e.g.:

```
(* scalar multiply, row-major *)
val smul : t -> float -> t
(* scalar multiply, column-major *)
val smulc : t -> float -> t
(* determinant, row-major *)
val det : t -> float
(* determinant, column-major *)
vat detc : t -> float
[...]
```

I'm having this weird feeling of becoming my father :) From the little bit of inertial nav theory he taught me, my intuitions go toward: right-handed coordinate systems (very strongly), ENU (weakly) and Tate-Bryan angles (strongly). I'm not to the point where any of these three make a difference in terms of the code I'm writing, yet, and if we haven't got the questions answered by the time they do matter, I'll create separate Issues for them.

zero-basis indices: agreed (note that this is a purely notational convention; we're using OCaml records rather than arrays to represent matrices, for speed. The usual indexing problem doesn't apply, it's just a matter of whether we refer to matrix elements as `e00, e01, e10, e11` or `e11, e12, e21, e22`)

**Comment by ab0032** [comment]
Agreed. I also feel very strongly about right handed coordinate systems.
Not using them would be insane even though I am left handed. And anyway the
memory layout should not need to worry us, it should be hidden under some
abstraction.

We should be dealing with rotations and translation, not with low level
representations. We should be dealing with transforms that take us from
drone coordinates to ground coordinates and the like.

Much software uses quaternions because they are more efficient.
https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation

**Comment by mikegogulski** [comment]
I'm going to go ahead and close this. We will stick with row-major as our primary representation, and add convenience methods to transform it into/out of column-major as required.

And yes, quaternions are coming.
